name = "Restaurant Hugo"
license = "MIT"
licenselink = "https://github.com/gethugothemes/restaurant-hugo/blob/master/LICENSE"
description = "The restaurant is a creative and responsive restaurant website theme in Hugo environment. It is very well decorated theme which will make your website building easier."
homepage = "https://gethugothemes.com/products/restaurant/"
demosite = "https://demo.gethugothemes.com/restaurant/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'business', 'agency-template', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'company', 'projects', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes']
features = ['bootstrap','responsive']
min_version = "0.62.0"

[author]
  name = "Gethugothemes"
  homepage = "https://gethugothemes.com/"
